"""
config.py — environment + secrets loader for the Gawd dashboard.

Reads:
  - ENV vars (port, exposure, novnc url, gateway url, log level)
  - ~/.gawd/.secrets/telegram.token        (per reference_bot_identities)
  - ~/.gawd/.secrets/dashboard_signing.key (auth token signing — generated by install.sh)
  - ~/.gawd/.secrets/fallback_ingest.key   (G2 shared secret — generated by install.sh)
  - ~/.gawd/state/identity.json            (chat_id of bound Prophit; populated at onboarding)

Hard rule (per feedback_diagnose_secrets_without_leaking_2026-04-25):
- NEVER log secret values. NEVER serialize a secret to a response. NEVER include in
  exception traces. Helpers below return token-existence booleans / opaque handles.
"""

from __future__ import annotations

import json
import logging
import os
import secrets as _secrets
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger("gawd.dashboard.config")

GAWD_HOME = Path(os.environ.get("GAWD_HOME", str(Path.home() / ".gawd")))
SECRETS_DIR = GAWD_HOME / ".secrets"
STATE_DIR = GAWD_HOME / "state"
WATCHDOG_STATE = STATE_DIR / "watchdog" / "last-sweep.json"
DASHBOARD_QUEUE_DIR = GAWD_HOME / "dashboard" / "queue"
DASHBOARD_PROCESSED_DIR = GAWD_HOME / "dashboard" / "processed"
TITHE_INTENTS_FILE = STATE_DIR / "tithe-intents.jsonl"
IDENTITY_FILE = STATE_DIR / "identity.json"

# Persona files (per A1)
PERSONA_DIR = GAWD_HOME / "persona"
USER_MD = PERSONA_DIR / "USER.md"
IDENTITY_MD = PERSONA_DIR / "IDENTITY.md"
SOUL_MD = PERSONA_DIR / "SOUL.md"

# Meeting canonical (B1) — looked up at runtime
MEETING_CANONICAL = GAWD_HOME / "meeting" / "canonical.md"


@dataclass(frozen=True)
class DashboardConfig:
    bind_host: str
    bind_port: int
    exposure: str          # local | tailscale | cloudflared
    gateway_url: str       # e.g., http://127.0.0.1:18789
    novnc_url: str | None  # e.g., https://your-machine.your-tailnet.ts.net/vnc.html
    log_level: str
    session_ttl_days: int
    silence_threshold_s: int
    # External base URL used for magic-link construction (no trailing slash).
    # Set via GAWD_DASHBOARD_EXTERNAL_URL. Falls back to a localhost URL if unset.
    external_url: str

    @property
    def has_novnc(self) -> bool:
        return bool(self.novnc_url)


def load_config() -> DashboardConfig:
    exposure = os.environ.get("GAWD_DASHBOARD_EXPOSURE", "local").lower()
    if exposure not in {"local", "tailscale", "cloudflared"}:
        log.warning("invalid GAWD_DASHBOARD_EXPOSURE=%r; falling back to 'local'", exposure)
        exposure = "local"

    # local + cloudflared bind loopback; tailscale binds 0.0.0.0 (tailnet-only).
    bind_host = "0.0.0.0" if exposure == "tailscale" else "127.0.0.1"
    bind_host = os.environ.get("GAWD_DASHBOARD_BIND_HOST", bind_host)

    bind_port = int(os.environ.get("GAWD_DASHBOARD_PORT", "8090"))
    # Default external URL: localhost (magic links won't be clickable, but won't crash).
    # Set GAWD_DASHBOARD_EXTERNAL_URL to the public-facing base (no trailing slash).
    external_url = (
        os.environ.get("GAWD_DASHBOARD_EXTERNAL_URL", "").rstrip("/")
        or f"http://127.0.0.1:{bind_port}"
    )

    return DashboardConfig(
        bind_host=bind_host,
        bind_port=bind_port,
        exposure=exposure,
        gateway_url=os.environ.get("GAWD_GATEWAY_URL", "http://127.0.0.1:18789"),
        novnc_url=os.environ.get("GAWD_NOVNC_URL") or None,
        log_level=os.environ.get("GAWD_LOG_LEVEL", "INFO"),
        session_ttl_days=int(os.environ.get("GAWD_SESSION_TTL_DAYS", "30")),
        silence_threshold_s=int(os.environ.get("GAWD_SILENCE_THRESHOLD_S", "30")),
        external_url=external_url,
    )


def read_secret_file(name: str) -> str | None:
    """
    Read a secret from ~/.gawd/.secrets/<name>. Returns the value or None.
    NEVER logs the value. Logs only existence + length.
    """
    path = SECRETS_DIR / name
    if not path.is_file():
        log.warning("secret missing: %s", name)
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            value = f.read().strip()
        log.debug("secret loaded: %s (length=%d)", name, len(value))
        return value or None
    except OSError as e:
        log.error("secret read failed: %s (%s)", name, type(e).__name__)
        return None


def get_telegram_token() -> str | None:
    """Telegram bot token. Lives in plain file per reference_bot_identities (Lilith pattern)."""
    return read_secret_file("telegram.token")


def get_signing_key() -> str:
    """
    Dashboard session/magic-link signing key. If missing, generate a one-shot
    in-memory key and warn loudly. Production: install.sh writes this once.
    """
    key = read_secret_file("dashboard_signing.key")
    if key:
        return key
    log.error(
        "dashboard_signing.key MISSING — generating one-shot in-memory key. "
        "Sessions will be invalidated on restart. Run install.sh."
    )
    return _secrets.token_urlsafe(32)


def get_fallback_ingest_key() -> str | None:
    """
    Shared secret between G2 deliver/dashboard.sh and the /api/fallback/ingest
    endpoint. Used for the SSE POST inbound path. If missing, ONLY the file-queue
    inbound path will work (still safe; file-queue is local-only).
    """
    return read_secret_file("fallback_ingest.key")


def get_bound_prophit_chat_id() -> int | None:
    """The Telegram chat_id of the Prophit bound to this Gawd. Set at onboarding."""
    if not IDENTITY_FILE.is_file():
        return None
    try:
        with open(IDENTITY_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        cid = data.get("prophit_telegram_chat_id")
        return int(cid) if cid is not None else None
    except (OSError, json.JSONDecodeError, ValueError) as e:
        log.warning("identity.json unreadable: %s", type(e).__name__)
        return None


def ensure_runtime_dirs() -> None:
    """Create runtime dirs idempotently. Called from app factory at startup."""
    for d in (STATE_DIR, DASHBOARD_QUEUE_DIR, DASHBOARD_PROCESSED_DIR, PERSONA_DIR):
        d.mkdir(parents=True, exist_ok=True)
    # secrets dir: 0700, never world-readable
    SECRETS_DIR.mkdir(parents=True, exist_ok=True)
    try:
        SECRETS_DIR.chmod(0o700)
    except OSError:
        pass
